services:
#    neo.example:
#        class: NeoBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    neo.nasa.service:
        class: NeoBundle\Service\NasaNeoService
        arguments:
            - "%nasa_api_url%"
            - "%nasa_api_key%"